description = "ubi 9 builder with no buildpacks included. To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/build-ubi9-base:0.0.10"

[lifecycle]
  version = "0.20.12"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/run-ubi9-base:latest"

[[targets]]
  arch = "amd64"
  os = "linux"
