name: Push Builder Image

on:
  release:
    types:
    - published

env:
  BUILDERS_FILEPATH: "builders.json"

jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-24.04
    outputs:
      builders: ${{ steps.get-builders.outputs.builders }}
      tag: ${{ steps.event.outputs.tag }}
      pack_version: ${{ steps.pack-version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

      # TODO: Add the image re on the buiders.json default
    - name: Get Builders
      id: get-builders
      run: |
        if [ -f ${{ env.BUILDERS_FILEPATH }} ]; then
          builders=$(jq -c '[.builders[] ]' ${{ env.BUILDERS_FILEPATH }} | jq -c '.[]')
        else
          builders=$(jq -n -c '[
              {
                "name": "default",
                "path": ".",
              }
            ]' | jq -c '.[]')
        fi
        echo "builders=${builders}" >> "$GITHUB_OUTPUT"

    - name: Parse Event
      id: event
      run: |
        echo "tag=$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)" >> "$GITHUB_OUTPUT"

  push:
    name: Push
    needs: preparation
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        builders: ${{ fromJSON(needs.preparation.outputs.builders) }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Builder Image and Push To Dockerhub
      env:
        PAKETO_BUILDPACKS_DOCKERHUB_USERNAME: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
        PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        DOCKERHUB_ORG="${GITHUB_REPOSITORY_OWNER/-/}" # translates 'paketo-buildpacks' to 'paketobuildpacks'
        container_repository=${{ matrix.builders.container_repository }}

        echo "${PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD}" | docker login --username "${PAKETO_BUILDPACKS_DOCKERHUB_USERNAME}" --password-stdin

        ./scripts/publish.sh --builder-toml-path "${{ matrix.builders.path }}/builder.toml" \
          --builder-image-ref "${DOCKERHUB_ORG}/${container_repository}:${{ needs.preparation.outputs.tag }}"

        crane copy "${DOCKERHUB_ORG}/${container_repository}:${{ needs.preparation.outputs.tag }}" "${DOCKERHUB_ORG}/${container_repository}:latest"

  failure:
    name: Alert on Failure
    runs-on: ubuntu-24.04
    needs: [push]
    if: ${{ always() && needs.push.result == 'failure' }}
    steps:
    - name: File Failure Alert Issue
      uses: paketo-buildpacks/github-config/actions/issue/file@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{ github.repository }}
        label: "failure:push"
        comment_if_exists: true
        issue_title: "Failure: Push Image workflow"
        issue_body: |
          Push Image workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
        comment_body: |
           Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
